### ISSUE TITLE
RuntimeError: dimension specified as 0 but tensor has no dimensions

### ISSUE THREAD

**Issue by jackkwok** [NVIDIA/flownet2-pytorch#102]
I am using python36-PyTorch0.4 branch with pytorch 0.4.0 and ran into the error when I run inference.  

`
python main.py --inference --name flownet --model FlowNet2S --save_flow --inference_dataset ImagesFromFolder --inference_dataset_root /home/jack/data/MPISintel/test/clean/ambush_1 --resume /home/jack/github/flownet2-pytorch/weights/FlowNet2-S_checkpoint.pth.tar --inference_batch_size 1
`

Is anyone else getting this error?

> /home/jack/anaconda3/envs/flownet2_old/lib/python3.6/site-packages/torch/nn/functional.py:1749: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
>   "See the documentation of nn.Upsample for details.".format(mode))
> Traceback (most recent call last):
>   File "main.py", line 408, in <module>
>     stats = inference(args=args, epoch=epoch - 1, data_loader=inference_loader, model=model_and_loss, offset=offset)
>   File "main.py", line 372, in inference
>     losses, output = model(data[0], target[0], inference=True)
>   File "/home/jack/anaconda3/envs/flownet2_old/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/jack/anaconda3/envs/flownet2_old/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 115, in forward
>     return self.gather(outputs, self.output_device)
>   File "/home/jack/anaconda3/envs/flownet2_old/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 127, in gather
>     return gather(outputs, output_device, dim=self.dim)
>   File "/home/jack/anaconda3/envs/flownet2_old/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
>     return gather_map(outputs)
>   File "/home/jack/anaconda3/envs/flownet2_old/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
>     return type(out)(map(gather_map, zip(*outputs)))
>   File "/home/jack/anaconda3/envs/flownet2_old/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
>     return type(out)(map(gather_map, zip(*outputs)))
>   File "/home/jack/anaconda3/envs/flownet2_old/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 55, in gather_map
>     return Gather.apply(target_device, dim, *outputs)
>   File "/home/jack/anaconda3/envs/flownet2_old/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 54, in forward
>     ctx.input_sizes = tuple(map(lambda i: i.size(ctx.dim), inputs))
>   File "/home/jack/anaconda3/envs/flownet2_old/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 54, in <lambda>
>     ctx.input_sizes = tuple(map(lambda i: i.size(ctx.dim), inputs))
> RuntimeError: dimension specified as 0 but tensor has no dimensions

**Comment by HopLee6** [comment]
This error occurs when a torch model returns a scaler (0 demension tensor) during multi-gpu training (one gpu is fine). So you have to convert the scaler to a one demension tensor when multi-gpu training.
Change line 177 and line 179 in main.py as follows
177: return [p.view(-1) for p in loss_values]
179: return [p.view(-1) for p in loss_values], output
