### ISSUE TITLE
NameError: global name 'channelnorm' is not defined

### ISSUE THREAD

**Issue by maria-ito** [NVIDIA/flownet2-pytorch#105]
Hi,

I am trying to train the model following the readme, and I can run one epoch, but then it crashes again. Can you please tell me what could be wrong?

Cheers

python main.py --batch_size 8 --model FlowNet2 --loss=L1Loss --optimizer=Adam --optimizer_lr=1e-4 --training_dataset MpiSintelFinal --training_dataset_root /media/maria/0C7ED7537ED733E4/Downloads-/inspiration_code/flownet2-pytorch/MPI-Sintel-complete/training  --validation_dataset MpiSintelClean --validation_dataset_root /media/maria/0C7ED7537ED733E4/Downloads-/inspiration_code/flownet2-pytorch/MPI-Sintel-complete/training

[...]

Overall Progress:   0%|                                                   | 0/10000 [00:00<?, ?it/s]/home/maria/anaconda2/lib/python2.7/site-packages/torch/nn/modules/upsampling.py:122: UserWarning: nn.Upsampling is deprecated. Use nn.functional.interpolate instead.            | 0/130.0 [00:00<?, ?it/s]
  warnings.warn("nn.Upsampling is deprecated. Use nn.functional.interpolate instead.")
/home/maria/anaconda2/lib/python2.7/site-packages/torch/nn/functional.py:1961: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
main.py:270: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  total_loss += loss_val.data[0]
main.py:271: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  loss_values = [v.data[0] for v in losses]
                                                                                                                        Traceback (most recent call last):
  File "main.py", line 426, in <module>457, load: 1.7e-05: 100%|█| 130/130.0 [01:48<00:00,  3.53it/s]
    train_loss, iterations = train(args=args, epoch=epoch, start_iteration=global_iteration, data_loader=train_loader, model=model_and_loss, optimizer=optimizer, logger=train_logger, offset=offset)
  File "main.py", line 292, in train                                                          | 0/130.0 [00:00<?, ?it/s]
    loss_val.backward()
  File "/home/maria/anaconda2/lib/python2.7/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/maria/anaconda2/lib/python2.7/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/maria/anaconda2/lib/python2.7/site-packages/torch/autograd/function.py", line 76, in apply
    return self._forward_cls.backward(self, *args)
  File "/media/maria/0C7ED7537ED733E4/Downloads-/inspiration_code/flownet2-pytorch/networks/channelnorm_package/channelnorm.py", line 25, in backward
    channelnorm.backward(input1, output, grad_output.data,
NameError: global name 'channelnorm' is not defined
Exception KeyError: KeyError(<weakref at 0x7fa2bcec9fc8; to 'tqdm' at 0x7fa2bc58c2d0>,) in <bound method tqdm.__del__ of Training Epoch 1:   0%|                                                                       | 0/130.0 [00:17<?, ?it/s]> ignored
Exception KeyError: KeyError(<weakref at 0x7fa2bcec92b8; to 'tqdm' at 0x7fa29810bc10>,) in <bound method tqdm.__del__ of Overall Progress:   0%|                                                   | 0/10000 [02:14<?, ?it/s]> ignored

**Comment by Kinpzz** [comment]
I have the same issue. I think this is a bug of naming. And someone has solve this problem in the pull request #94 .
