### ISSUE TITLE
Cannot install the package

### ISSUE THREAD

**Issue by ADHARACSM** [NVIDIA/flownet2-pytorch#109]
nvcc: NVIDIA (R) Cuda compiler driver
Cuda compilation tools, release 9.0, V9.0.176
Torch version 0.4.1
Windows 10 Home Edition

When I run the python main.py,

(pytorch) D:\CSM\Spring2019\flownet2-pytorch>python main.py --help
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    import models, losses, datasets
  File "D:\CSM\Spring2019\flownet2-pytorch\models.py", line 8, in <module>
    from networks.resample2d_package.resample2d import Resample2d
  File "D:\CSM\Spring2019\flownet2-pytorch\networks\resample2d_package\resample2d.py", line 3, in <module>
    import resample2d_cuda
ModuleNotFoundError: No module named 'resample2d_cuda'

When I run bash install.sh

: No such file or directoryetworks/correlation_package
python: can't open file 'setup.py': [Errno 2] No such file or directory
install.sh: line 4: cd: ../resample2d_package: No such file or directory
python: can't open file 'setup.py': [Errno 2] No such file or directory
install.sh: line 6: cd: ../channelnorm_package: No such file or directory
python: can't open file 'setup.py': [Errno 2] No such file or directory
: No such file or directory

**Comment by huangbiubiu** [comment]
Change your linebreak to `LF` on linux.

**Comment by GUWOGANSHOU** [comment]
I also encountered this error. Did you find any solution for it？

**Comment by GUWOGANSHOU** [comment]
> Change your linebreak to `LF` on linux.

I just run on windows.

**Comment by huangbiubiu** [comment]
> > Change your linebreak to `LF` on linux.
> 
> I just run on windows.

If you use `bash` on Windows, you still need to use `LF` instead of `CRLF`. The git will automatically use `CRLF` on Windows, which will raise an error in `bash`.
