### ISSUE TITLE
resample2d_cuda _ZN2at19UndefinedTensorImpl10_singletonE

### ISSUE THREAD

**Issue by jiapei100** [NVIDIA/flownet2-pytorch#116]
Failed to import resample2d_cuda

```
➜  ~ python
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import correlation_cuda
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: ~/.local/lib/python3.6/site-packages/correlation_cuda-0.0.0-py3.6-linux-x86_64.egg/correlation_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE
>>> import channelnorm_cuda
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: ~/.local/lib/python3.6/site-packages/channelnorm_cuda-0.0.0-py3.6-linux-x86_64.egg/channelnorm_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE
>>> import resample2d_cuda
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: ~/.local/lib/python3.6/site-packages/resample2d_cuda-0.0.0-py3.6-linux-x86_64.egg/resample2d_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE
>>>
```

**Comment by jiapei100** [comment]
Solved:

```
import torch
```

**FIRST**

**Comment by jakubLangr** [comment]
In my case it does not help:
```
python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import resample2d_cuda
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/ubuntu/.local/lib/python3.6/site-packages/resample2d_cuda-0.0.0-py3.6-linux-x86_64.egg/resample2d_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104impl28tls_excluded_tensor_type_setEv
```
anyone else encountered this error?

**Comment by birdflyto** [comment]
> In my case it does not help:
> 
> ```
> python
> Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
> [GCC 7.2.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import torch
> >>> import resample2d_cuda
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: /home/ubuntu/.local/lib/python3.6/site-packages/resample2d_cuda-0.0.0-py3.6-linux-x86_64.egg/resample2d_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104impl28tls_excluded_tensor_type_setEv
> ```
> 
> anyone else encountered this error?
 
have you solved the problem ,the problem has confused me for several days.

**Comment by jakubLangr** [comment]
No, still waiting. @jiapei100 maybe could help?
