### ISSUE TITLE
How to use the pretrained model?

### ISSUE THREAD

**Issue by MingPap** [NVIDIA/flownet2-pytorch#117]
Hi~

I'm new to use pytorch, could you tell me how to test if the flownet2 works?

I mean there must be  path of a pair of photos as input.

But I don't find it in the reference code.

help wanted!

**Comment by huangbiubiu** [comment]
Try 
```
python main.py --inference --model FlowNet2 --save_flow --save /path/to/result/ --inference_dataset ImagesFromFolder --inference_dataset_root /path/to/test/data/sequence --resume /path/to/model/FlowNet2_checkpoint.pth.tar
```

No need to download MpiSintel dataset if you just want to inference.

**Comment by tianbartek** [comment]
@huangbiubiu I tried the way you said, but it didn't work.  I used MPI final as inference dataset. But I got 
          
         self.frame_size = frame_utils.read_gen(self.image_list[0][0]).shape
IndexError: list index out of range

Do you have any suggestion?

**Comment by huangbiubiu** [comment]
@tianbartek seems there was something error when loading images from your dataset path. I guess maybe you should change the parameter `iext` of the class `ImagesFromFolder`.

**Comment by tianbartek** [comment]
@huangbiubiu Sorry, I don't understand how to do it. Can you be more specific?  For me, my loading path is: '../MPI-Sintel/MPI-Sintel-complete/test/final'

**Comment by tianbartek** [comment]
@huangbiubiu BTW, have you run successfully?

**Comment by Miss-Li97** [comment]
Building FlowNet2 model
  [3.970s] Effective Batch Size: 16
  [3.970s] Number of parameters: 162518834
  [3.970s] Initializing CUDA
  [8.210s] Parallelizing
  [8.210s] Loading checkpoint '/home/lihanyu/PycharmProjects/flownet2-pytorch-master/parameter/FlowNet2-CS_checkpoint.pth.tar'
  [8.600s] Operation failed

Traceback (most recent call last):
  File "main.py", line 212, in <module>
    model_and_loss.module.model.load_state_dict(checkpoint['state_dict'])
  File "/home/lihanyu/Envs/test/lib/python3.6/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for FlowNet2:
        Missing key(s) in state_dict: "flownets_2.conv1.0.weight", "flownets_2.conv1.0.bias", "flownets_2.conv2.0.weight", "flownets_2.conv2.0.bias", "flownets_2.conv3.0.weight", "flownets_2.conv3.0.bias", "flownets_2.conv3_1.0.weight", "flownets_2.conv3_1.0.bias", "flownets_2.conv4.0.weight", "flownets_2.conv4.0.bias", "flownets_2.conv4_1.0.weight", "flownets_2.conv4_1.0.bias", "flownets_2.conv5.0.weight", "flownets_2.conv5.0.bias", "flownets_2.conv5_1.0.weight", "flownets_2.conv5_1.0.bias", "flownets_2.conv6.0.weight", "flownets_2.conv6.0.bias", "flownets_2.conv6_1.0.weight", "flownets_2.conv6_1.0.bias", "flownets_2.deconv5.0.weight", "flownets_2.deconv5.0.bias", "flownets_2.deconv4.0.weight", "flownets_2.deconv4.0.bias", "flownets_2.deconv3.0.weight", "flownets_2.deconv3.0.bias", "flownets_2.deconv2.0.weight", "flownets_2.deconv2.0.bias", "flownets_2.predict_flow6.weight", "flownets_2.predict_flow6.bias", "flownets_2.predict_flow5.weight", "flownets_2.predict_flow5.bias", "flownets_2.predict_flow4.weight", "flownets_2.predict_flow4.bias", "flownets_2.predict_flow3.weight", "flownets_2.predict_flow3.bias", "flownets_2.predict_flow2.weight", "flownets_2.predict_flow2.bias", "flownets_2.upsampled_flow6_to_5.weight", "flownets_2.upsampled_flow5_to_4.weight", "flownets_2.upsampled_flow4_to_3.weight", "flownets_2.upsampled_flow3_to_2.weight", "flownets_d.conv0.0.weight", "flownets_d.conv0.0.bias", "flownets_d.conv1.0.weight", "flownets_d.conv1.0.bias", "flownets_d.conv1_1.0.weight", "flownets_d.conv1_1.0.bias", "flownets_d.conv2.0.weight", "flownets_d.conv2.0.bias", "flownets_d.conv2_1.0.weight", "flownets_d.conv2_1.0.bias", "flownets_d.conv3.0.weight", "flownets_d.conv3.0.bias", "flownets_d.conv3_1.0.weight", "flownets_d.conv3_1.0.bias", "flownets_d.conv4.0.weight", "flownets_d.conv4.0.bias", "flownets_d.conv4_1.0.weight", "flownets_d.conv4_1.0.bias", "flownets_d.conv5.0.weight", "flownets_d.conv5.0.bias", "flownets_d.conv5_1.0.weight", "flownets_d.conv5_1.0.bias", "flownets_d.conv6.0.weight", "flownets_d.conv6.0.bias", "flownets_d.conv6_1.0.weight", "flownets_d.conv6_1.0.bias", "flownets_d.deconv5.0.weight", "flownets_d.deconv5.0.bias", "flownets_d.deconv4.0.weight", "flownets_d.deconv4.0.bias", "flownets_d.deconv3.0.weight", "flownets_d.deconv3.0.bias", "flownets_d.deconv2.0.weight", "flownets_d.deconv2.0.bias", "flownets_d.inter_conv5.0.weight", "flownets_d.inter_conv5.0.bias", "flownets_d.inter_conv4.0.weight", "flownets_d.inter_conv4.0.bias", "flownets_d.inter_conv3.0.weight", "flownets_d.inter_conv3.0.bias", "flownets_d.inter_conv2.0.weight", "flownets_d.inter_conv2.0.bias", "flownets_d.predict_flow6.weight", "flownets_d.predict_flow6.bias", "flownets_d.predict_flow5.weight", "flownets_d.predict_flow5.bias", "flownets_d.predict_flow4.weight", "flownets_d.predict_flow4.bias", "flownets_d.predict_flow3.weight", "flownets_d.predict_flow3.bias", "flownets_d.predict_flow2.weight", "flownets_d.predict_flow2.bias", "flownets_d.upsampled_flow6_to_5.weight", "flownets_d.upsampled_flow6_to_5.bias", "flownets_d.upsampled_flow5_to_4.weight", "flownets_d.upsampled_flow5_to_4.bias", "flownets_d.upsampled_flow4_to_3.weight", "flownets_d.upsampled_flow4_to_3.bias", "flownets_d.upsampled_flow3_to_2.weight", "flownets_d.upsampled_flow3_to_2.bias", "flownetfusion.conv0.0.weight", "flownetfusion.conv0.0.bias", "flownetfusion.conv1.0.weight", "flownetfusion.conv1.0.bias", "flownetfusion.conv1_1.0.weight", "flownetfusion.conv1_1.0.bias", "flownetfusion.conv2.0.weight", "flownetfusion.conv2.0.bias", "flownetfusion.conv2_1.0.weight", "flownetfusion.conv2_1.0.bias", "flownetfusion.deconv1.0.weight", "flownetfusion.deconv1.0.bias", "flownetfusion.deconv0.0.weight", "flownetfusion.deconv0.0.bias", "flownetfusion.inter_conv1.0.weight", "flownetfusion.inter_conv1.0.bias", "flownetfusion.inter_conv0.0.weight", "flownetfusion.inter_conv0.0.bias", "flownetfusion.predict_flow2.weight", "flownetfusion.predict_flow2.bias", "flownetfusion.predict_flow1.weight", "flownetfusion.predict_flow1.bias", "flownetfusion.predict_flow0.weight", "flownetfusion.predict_flow0.bias", "flownetfusion.upsampled_flow2_to_1.weight", "flownetfusion.upsampled_flow2_to_1.bias", "flownetfusion.upsampled_flow1_to_0.weight", "flownetfusion.upsampled_flow1_to_0.bias". 

did you meet this question?can you help me ?

**Comment by fperezgamonal** [comment]
Hi @Miss-Li97 

I think the problem is that you are trying to load the weights from the `FlowNet2-CS_checkpoint.pth.tar` but with the flag `--model FlowNet2`. As a result, PyTorch is trying to load the weights into a different architecture (FlowNet2) which fails.

I think you can fix this by doing one of the following depending on your initial intentions:

1.  If you want to run inference on the _FlowNet2-CS_ model, then you need to use the same command but replace `--model FlowNet2` by `--model FlowNet2CS` (search `main.py`.
2. Otherwise, if you intended to run inference on the _FlowNet2_ model, you must change the `--resume path/to/FlowNet2CS.pth.tar` to `--resume path/to/FlowNet2.pth.tar`.

The problem is that I cannot test this since I am having the error described by @tianbartek and I'm still trying to fix it.

Hopefully you are able to fix the loading and not run into the reading problem we are facing.

My reasoning behind the proposed solution:
 The thing is that the parameter `--model` gets passed directly to the module `models.py` by using `utils/tools.py: add_arguments_for_module` (I started using classes for python few months ago so do not 100% trust me on this one), which is called in `main.py`. 

Regards,
Ferran.

**Comment by Miss-Li97** [comment]
@fperezgamonal
Thanks for you reply,you are right. I have finished this question

**Comment by lisitodyb** [comment]
Hi @fperezgamonal 
I fixed the problem of loading,but It's no progress in Inferencing without an error message when running the main.py.
specifically,it shows that.

Initializing Adam Optimizer
  [0.000s] amsgrad = False (<class 'bool'>)
  [0.000s] weight_decay = 0 (<class 'int'>)
  [0.000s] eps = 1e-08 (<class 'float'>)
  [0.000s] betas = (0.9, 0.999) (<class 'tuple'>)
  [0.000s] lr = 0.001 (<class 'float'>)
  [0.000s] Operation finished

Overall Progress:   0%|                                                       | 0/1 [00:00<?, ?it/s]
Inferencing :   0%|                                                        | 0/24.0 [00:00<?, ?it/s]

**Comment by Jeason1015** [comment]
Hello, I am also a newbie. I want to do the same thing as you. In the face of such parameters, I can't figure out how to simply enter two images to get a Flow image or get a warp image. I saw that you are also a Chinese. Can you consult with us for your experience? Can you have your WeChat?

**Comment by leeeeeeo** [comment]
@huangbiubiu gave the solution [https://github.com/NVIDIA/flownet2-pytorch/issues/117#issuecomment-457245937].
Replace `--inference_dataset MpiSintelClean` with `--inference_dataset ImagesFromFolder`

**Comment by leeeeeeo** [comment]
python main.py
--inference
--model FlowNet2
--save_flow
--save ./output
--inference_dataset ImagesFromFolder
--inference_dataset_root ./data/MPI-Sintel-testing/test/clean/wall
--resume ./models/FlowNet2_checkpoint.pth.tar

Try this!

**Comment by HongguLiu** [comment]
> Hello, I am also a newbie. I want to do the same thing as you. In the face of such parameters, I can't figure out how to simply enter two images to get a Flow image or get a warp image. I saw that you are also a Chinese. Can you consult with us for your experience? Can you have your WeChat?

You can get the .flo file if you run 'python main.py --inference .....' directly, but I also don't know how to warp.

**Comment by gmy1234** [comment]
> 您好，我也是新手。我想和你做同样的事情。面对这样的参数，我想不通如何简单地输入两个图像来获得流图像或扭曲图像。我看到你也是中国人。您可以向我们咨询您的经验吗？您可以使用微信吗？

你好，你的解决了吗？

**Comment by yjhdhr** [comment]
> > 您好，我也是新手。我想和你做同样的事情。面对这样的参数，我想不通如何简单地输入两个图像来获得流图像或扭曲图像。我看到你也是中国人。您可以向我们咨询您的经验吗？您可以使用微信吗？
> 
> 你好，你的解决了吗？

可以讨论下吗？加我V : yjhdhr
