### ISSUE TITLE
Does anyone use the single image pair mode code to get some correct result.

### ISSUE THREAD

**Issue by MaureenZOU** [NVIDIA/flownet2-pytorch#129]
I try the single image pair code in https://github.com/NVIDIA/flownet2-pytorch/issues/51 and download flownet2 pretrained network. It seems that all the output I produce is really small around 1e-2 (I have make sure I load the data correctly.)

Does anyone meet the same issue?

**Comment by tianbartek** [comment]
Have you found the right way?

**Comment by davinca** [comment]
```python
Traceback (most recent call last):
  File "run_a_pair.py", line 34, in <module>
    result = net(im).squeeze()
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 16 and 15 in dimension 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:71
```
I run the `run_a_pair.py`, but error like above occur, how can I solve it?

**Comment by semchan** [comment]
> ```python
> Traceback (most recent call last):
>   File "run_a_pair.py", line 34, in <module>
>     result = net(im).squeeze()
> RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 16 and 15 in dimension 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:71
> ```
> 
> I run the `run_a_pair.py`, but error like above occur, how can I solve it?

did you fixed it? thanks

**Comment by WinstonDeng** [comment]
@davinca @semchan Hi, I met the same issue but have fixed it.
When I input a pair with the size of (320,480,3), the error occurs. 
After resizing input to (640,960,3), it' ok.
So the reason may be input size is smaller than the model filter's size. Try to resize the input.
