### ISSUE TITLE
how to use the pretrained model?

### ISSUE THREAD

**Issue by Miss-Li97** [NVIDIA/flownet2-pytorch#133]
Building FlowNet2 model
  [3.970s] Effective Batch Size: 16
  [3.970s] Number of parameters: 162518834
  [3.970s] Initializing CUDA
  [8.210s] Parallelizing
  [8.210s] Loading checkpoint '/home/lihanyu/PycharmProjects/flownet2-pytorch-master/parameter/FlowNet2-CS_checkpoint.pth.tar'
  [8.600s] Operation failed

Traceback (most recent call last):
  File "main.py", line 212, in <module>
    model_and_loss.module.model.load_state_dict(checkpoint['state_dict'])
  File "/home/lihanyu/Envs/test/lib/python3.6/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for FlowNet2:
        Missing key(s) in state_dict: "flownets_2.conv1.0.weight", "flownets_2.conv1.0.bias", "flownets_2.conv2.0.weight", "flownets_2.conv2.0.bias", "flownets_2.conv3.0.weight", "flownets_2.conv3.0.bias", "flownets_2.conv3_1.0.weight", "flownets_2.conv3_1.0.bias", "flownets_2.conv4.0.weight", "flownets_2.conv4.0.bias", "flownets_2.conv4_1.0.weight", "flownets_2.conv4_1.0.bias", "flownets_2.conv5.0.weight", "flownets_2.conv5.0.bias", "flownets_2.conv5_1.0.weight", "flownets_2.conv5_1.0.bias", "flownets_2.conv6.0.weight", "flownets_2.conv6.0.bias", "flownets_2.conv6_1.0.weight", "flownets_2.conv6_1.0.bias", "flownets_2.deconv5.0.weight", "flownets_2.deconv5.0.bias", "flownets_2.deconv4.0.weight", "flownets_2.deconv4.0.bias", "flownets_2.deconv3.0.weight", "flownets_2.deconv3.0.bias", "flownets_2.deconv2.0.weight", "flownets_2.deconv2.0.bias", "flownets_2.predict_flow6.weight", "flownets_2.predict_flow6.bias", "flownets_2.predict_flow5.weight", "flownets_2.predict_flow5.bias", "flownets_2.predict_flow4.weight", "flownets_2.predict_flow4.bias", "flownets_2.predict_flow3.weight", "flownets_2.predict_flow3.bias", "flownets_2.predict_flow2.weight", "flownets_2.predict_flow2.bias", "flownets_2.upsampled_flow6_to_5.weight", "flownets_2.upsampled_flow5_to_4.weight", "flownets_2.upsampled_flow4_to_3.weight", "flownets_2.upsampled_flow3_to_2.weight", "flownets_d.conv0.0.weight", "flownets_d.conv0.0.bias", "flownets_d.conv1.0.weight", "flownets_d.conv1.0.bias", "flownets_d.conv1_1.0.weight", "flownets_d.conv1_1.0.bias", "flownets_d.conv2.0.weight", "flownets_d.conv2.0.bias", "flownets_d.conv2_1.0.weight", "flownets_d.conv2_1.0.bias", "flownets_d.conv3.0.weight", "flownets_d.conv3.0.bias", "flownets_d.conv3_1.0.weight", "flownets_d.conv3_1.0.bias", "flownets_d.conv4.0.weight", "flownets_d.conv4.0.bias", "flownets_d.conv4_1.0.weight", "flownets_d.conv4_1.0.bias", "flownets_d.conv5.0.weight", "flownets_d.conv5.0.bias", "flownets_d.conv5_1.0.weight", "flownets_d.conv5_1.0.bias", "flownets_d.conv6.0.weight", "flownets_d.conv6.0.bias", "flownets_d.conv6_1.0.weight", "flownets_d.conv6_1.0.bias", "flownets_d.deconv5.0.weight", "flownets_d.deconv5.0.bias", "flownets_d.deconv4.0.weight", "flownets_d.deconv4.0.bias", "flownets_d.deconv3.0.weight", "flownets_d.deconv3.0.bias", "flownets_d.deconv2.0.weight", "flownets_d.deconv2.0.bias", "flownets_d.inter_conv5.0.weight", "flownets_d.inter_conv5.0.bias", "flownets_d.inter_conv4.0.weight", "flownets_d.inter_conv4.0.bias", "flownets_d.inter_conv3.0.weight", "flownets_d.inter_conv3.0.bias", "flownets_d.inter_conv2.0.weight", "flownets_d.inter_conv2.0.bias", "flownets_d.predict_flow6.weight", "flownets_d.predict_flow6.bias", "flownets_d.predict_flow5.weight", "flownets_d.predict_flow5.bias", "flownets_d.predict_flow4.weight", "flownets_d.predict_flow4.bias", "flownets_d.predict_flow3.weight", "flownets_d.predict_flow3.bias", "flownets_d.predict_flow2.weight", "flownets_d.predict_flow2.bias", "flownets_d.upsampled_flow6_to_5.weight", "flownets_d.upsampled_flow6_to_5.bias", "flownets_d.upsampled_flow5_to_4.weight", "flownets_d.upsampled_flow5_to_4.bias", "flownets_d.upsampled_flow4_to_3.weight", "flownets_d.upsampled_flow4_to_3.bias", "flownets_d.upsampled_flow3_to_2.weight", "flownets_d.upsampled_flow3_to_2.bias", "flownetfusion.conv0.0.weight", "flownetfusion.conv0.0.bias", "flownetfusion.conv1.0.weight", "flownetfusion.conv1.0.bias", "flownetfusion.conv1_1.0.weight", "flownetfusion.conv1_1.0.bias", "flownetfusion.conv2.0.weight", "flownetfusion.conv2.0.bias", "flownetfusion.conv2_1.0.weight", "flownetfusion.conv2_1.0.bias", "flownetfusion.deconv1.0.weight", "flownetfusion.deconv1.0.bias", "flownetfusion.deconv0.0.weight", "flownetfusion.deconv0.0.bias", "flownetfusion.inter_conv1.0.weight", "flownetfusion.inter_conv1.0.bias", "flownetfusion.inter_conv0.0.weight", "flownetfusion.inter_conv0.0.bias", "flownetfusion.predict_flow2.weight", "flownetfusion.predict_flow2.bias", "flownetfusion.predict_flow1.weight", "flownetfusion.predict_flow1.bias", "flownetfusion.predict_flow0.weight", "flownetfusion.predict_flow0.bias", "flownetfusion.upsampled_flow2_to_1.weight", "flownetfusion.upsampled_flow2_to_1.bias", "flownetfusion.upsampled_flow1_to_0.weight", "flownetfusion.upsampled_flow1_to_0.bias". 

can you help me solve  this problem???

**Comment by leeeeeeo** [comment]
--model **FlowNet2** should be same with --resume ./models/**FlowNet2**_checkpoint.pth.tar
