### ISSUE TITLE
Windows 10 Installation?

### ISSUE THREAD

**Issue by hoemon** [NVIDIA/flownet2-pytorch#145]
Is there any workaround for windows 10 installation?
install.sh does not seem to work for windows, or maybe, I'm missing something.

**Comment by huangbiubiu** [comment]
I think `install.sh` will work well on Windows. All commands in `install.sh` is supported by Windows (`cd` and `python`). If there is an error, please do paste your error message, or we can not give any useful help.

**Comment by tjusxh** [comment]
My environment as following, Windows10, Pytorch0.4.1 CUDA0.9.  When I bash install.sh, I have the following error.
E:\Program Files\Python35\lib\site-packages\torch\lib\include\ATen/Error.h(69): warning C4275: ▒▒ dll ▒ӿ▒ class▒▒std::exception▒▒▒▒▒▒ dll ▒ӿ▒ class▒▒at::Error▒▒▒Ļ▒
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\vcruntime_exception.h(43): note: ▒μ▒▒▒std::exception▒▒▒▒▒▒▒▒
E:\Program Files\Python35\lib\site-packages\torch\lib\include\ATen/Error.h(69): note: ▒μ▒▒▒at::Error▒▒▒▒▒▒▒▒
E:\Program Files\Python35\lib\site-packages\torch\lib\include\ATen/Error.h(70): warning C4251: ▒▒at::Error::what_without_backtrace_▒▒: class▒▒std::basic_string<char,std::char_traits<char>,std::allocator<char>>▒▒▒▒Ҫ▒▒ dll ▒ӿ▒▒▒ class▒▒at::Error▒▒▒Ŀͻ▒▒▒ʹ▒▒
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\xstring(2633): note: ▒μ▒▒▒std::basic_string<char,std::char_traits<char>,std::allocator<char>>▒▒▒▒▒▒▒▒
E:\Program Files\Python35\lib\site-packages\torch\lib\include\ATen/Error.h(71): warning C4251: ▒▒at::Error::what_▒▒: class▒▒std::basic_string<char,std::char_traits<char>,std::allocator<char>>▒▒▒▒Ҫ▒▒ dll ▒ӿ▒▒▒ class▒▒at::Error▒▒▒Ŀͻ▒▒▒ʹ▒▒
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\xstring(2633): note: ▒μ▒▒▒std::basic_string<char,std::char_traits<char>,std::allocator<char>>▒▒▒▒▒▒▒▒

Please  Any error happened When I configuring the environment? Thanks very much.

**Comment by tjusxh** [comment]
I configured environment pytorch0.4.1 python3.6 cuda9.0 by anaconda. But I run install.sh, I also encounter the same issue. Any help to me, I will be deeply grateful.


correlation_cuda.cc(4): fatal error C1083: 无法打开包括文件: “ATen/cuda/CUDAContext.h”: No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Comment by tjusxh** [comment]
“ATen/cuda/CUDAContext.h”: No such file or directory. I solve the question by install pytorch1.0.1. The readme maybe not correspond with the code.

**Comment by tjusxh** [comment]
@hoemon  
 When I compile the network project on Winndows. I have the following error. How to resolve the question?
E:\Program Files\Python35\lib\site-packages\torch\utils\cpp_extension.py:80: UserWarning: Error checking compiler version: [WinError 2] 
  warnings.warn('Error checking compiler version: {}'.format(error))
E:\Program Files\Python35\lib\site-packages\torch\utils\cpp_extension.py:106: UserWarning:

**Comment by mathieumb** [comment]
@tjusxh

You need to make sure your C++ compiler (e.g. cl.exe if visual studio ) in is your PATH environment variable.

**Comment by JiangYi0311** [comment]
I configured environment pytorch1.1.0 python3.6 cuda9.0 by anaconda
When I compile the network project on Winndows. I have the following error. How to resolve the question?
Traceback (most recent call last):
  File "build.py", line 28, in <module>
    extra_objects=[os.path.join(this_folder, Object) for Object in Objects]
  File "C:\Installation\Anaconda3\envs\pytorch-l\lib\site-packages\torch\utils\cpp_extension.py", line 228, in __init__
    super(BuildExtension, self).__init__(*args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'dist'

**Comment by openSourcerer9000** [comment]
I installed visual studio community 2022, and added `C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\Hostx86\x64` to PATH, which includes a `cl.exe`.

This is what I get:
```(fvid) flownet2_pytorch\networks\correlation_package>python setup.py install --user
No CUDA runtime is found, using CUDA_HOME='C:\Users\me\anaconda3\envs\fvid\Library'
running install
C:\Users\me\anaconda3\envs\fvid\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
C:\Users\me\anaconda3\envs\fvid\lib\site-packages\setuptools\_distutils\cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing correlation_cuda.egg-info\PKG-INFO
writing dependency_links to correlation_cuda.egg-info\dependency_links.txt
writing top-level names to correlation_cuda.egg-info\top_level.txt
C:\Users\me\anaconda3\envs\fvid\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'correlation_cuda.egg-info\SOURCES.txt'
writing manifest file 'correlation_cuda.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
C:\Users\me\anaconda3\envs\fvid\lib\site-packages\torch\utils\cpp_extension.py:358: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    'build_ext': BuildExtension
  File "C:\Users\me\anaconda3\envs\fvid\lib\site-packages\setuptools\__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\me\anaconda3\envs\fvid\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "C:\Users\me\anaconda3\envs\fvid\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Users\me\anaconda3\envs\fvid\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "C:\Users\me\anaconda3\envs\fvid\lib\site-packages\setuptools\dist.py", line 1233, in run_command
    super().run_command(command)
  File "C:\Users\me\anaconda3\envs\fvid\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\me\anaconda3\envs\fvid\lib\site-packages\setuptools\command\install.py", line 84, in run
    self.do_egg_install()
  File "C:\Users\me\anaconda3\envs\fvid\lib\site-packages\setuptools\command\install.py", line 132, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\me\anaconda3\envs\fvid\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\Users\me\anaconda3\envs\fvid\lib\site-packages\setuptools\dist.py", line 1233, in run_command
    super().run_command(command)
  File "C:\Users\me\anaconda3\envs\fvid\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\me\anaconda3\envs\fvid\lib\site-packages\setuptools\command\bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\me\anaconda3\envs\fvid\lib\site-packages\setuptools\command\bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "C:\Users\me\anaconda3\envs\fvid\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\Users\me\anaconda3\envs\fvid\lib\site-packages\setuptools\dist.py", line 1233, in run_command
    super().run_command(command)
  File "C:\Users\me\anaconda3\envs\fvid\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\me\anaconda3\envs\fvid\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\me\anaconda3\envs\fvid\lib\site-packages\setuptools\_distutils\command\install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "C:\Users\me\anaconda3\envs\fvid\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\Users\me\anaconda3\envs\fvid\lib\site-packages\setuptools\dist.py", line 1233, in run_command
    super().run_command(command)
  File "C:\Users\me\anaconda3\envs\fvid\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\me\anaconda3\envs\fvid\lib\site-packages\setuptools\command\build_ext.py", line 88, in run
    _build_ext.run(self)
  File "C:\Users\me\anaconda3\envs\fvid\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
    self.build_extensions()
  File "C:\Users\me\anaconda3\envs\fvid\lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
    _check_cuda_version(compiler_name, compiler_version)
  File "C:\Users\me\anaconda3\envs\fvid\lib\site-packages\torch\utils\cpp_extension.py", line 382, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
  File "C:\Users\me\anaconda3\envs\fvid\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 52, in parse
    return Version(version)
  File "C:\Users\me\anaconda3\envs\fvid\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 196, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object```
