### ISSUE TITLE
assert all(map(lambda i: i.is_cuda, inputs)) AssertionError when training FlowNet2C

### ISSUE THREAD

**Issue by realtc** [NVIDIA/flownet2-pytorch#146]
I am trying to train FlowNet2C with a dataset like FlyingChairs format. got te following error, anyone has idea what might cause it? (I am using the latest pytorch):

raining Epoch 0:   Traceback (most recent call last):                                        | 0/12  File "main.py", line 419, in <module>
    is_validate=False, offset=offset) 
  File "main.py", line 269, in train
    losses = model(data[0], target[0])
  File "/home/tchen/anaconda2/envs/env3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tchen/anaconda2/envs/env3.6/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 144, in forward
    return self.gather(outputs, self.output_device)
  File "/home/tchen/anaconda2/envs/env3.6/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 156, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/tchen/anaconda2/envs/env3.6/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 67, in gather
    return gather_map(outputs)
  File "/home/tchen/anaconda2/envs/env3.6/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 62, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/home/tchen/anaconda2/envs/env3.6/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 54, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "/home/tchen/anaconda2/envs/env3.6/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 54, in forward
    **assert all(map(lambda i: i.is_cuda, inputs))
AssertionError**

-------------------
Here is the script: 
!/bin/bash 
size=256
python main.py --batch_size 4 --model FlowNet2C \
--loss=MultiScale --optimizer=Adam --optimizer_lr=1e-4 \
--crop_size 256 256 --loss_numScales=5 --loss_startScale=4 \
--training_dataset OatDataSet \
--training_dataset_root /home/data2/panda3d/panda3dWork/train${size}x${size}x4x10000 \
--validation_dataset OatDataSet \
--validation_dataset_root /home/data2/panda3d/panda3dWork/val${size}x${size}x4x1000 \
--inference_dataset_root ''

**Comment by Kolin96** [comment]
I came across the same problem, and I solved it by modifying the MultiScale class code. I was using the latest CUDA 10 and pytorch 1.1.0, so I'm not sure whether my solution would help you or not if you use different versions.

I think the reason for this problem lies in the MultiScale class implementation. The forward function initializes lossvalue and epevalue as 0, which is not a cuda variable. Since we have parallelized the ModelAndLoss module, the outputs of the loss function should be in cuda; otherwise, we can't gather the outputs from multiple cuda devices and hence get this assertion error. Therefore, I changed the forward function as follows, and the new code works in my case.
`def forward(self, output, target):
        if type(output) is tuple:
            target = self.div_flow * target
            for i, output_ in enumerate(output):
                target_ = self.multiScales[i](target)
                if i == 0:
                    epevalue = EPE(output_, target_) * self.loss_weights[i]
                    lossvalue = self.loss(output_, target_) * self.loss_weights[i]
                else:
                    epevalue += EPE(output_, target_) * self.loss_weights[i]
                    lossvalue += self.loss(output_, target_) * self.loss_weights[i]
            return [lossvalue, epevalue]
        else:
            epevalue = EPE(output, target)
            lossvalue = self.loss(output, target)
            return  [lossvalue, epevalue]`

Also, note that there is another typo in the MultiScale class: in the definition of self.loss_labels, there is a redundant comma at the end of the line, which may cause some unexpected errors.

**Comment by ujsyehao** [comment]
@Kolin96 Can you explain it in more detail?
