### ISSUE TITLE
fatal error run bash insatll.sh

### ISSUE THREAD

**Issue by xuleyoung** [NVIDIA/flownet2-pytorch#156]
Hi, when I run bash install.sh
There are some problems, I don't know how to solve it, please help me, Thank you.
unning install_lib
running build_ext
building 'correlation_cuda' extension
gcc -pthread -B /media/data2/xly/anaconda3/envs/py36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/media/data2/xly/anaconda3/envs/py36/lib/python3.6/site-packages/torch/lib/include -I/media/data2/xly/anaconda3/envs/py36/lib/python3.6/site-packages/torch/lib/include/TH -I/media/data2/xly/anaconda3/envs/py36/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/media/data2/xly/anaconda3/envs/py36/include/python3.6m -c correlation_cuda.cc -o build/temp.linux-x86_64-3.6/correlation_cuda.o -std=c++11 -DTORCH_EXTENSION_NAME=correlation_cuda
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
correlation_cuda.cc:4:35: fatal error: ATen/cuda/CUDAContext.h: No such file or directory
 #include <ATen/cuda/CUDAContext.h>
                                   ^
compilation terminated.
error: command 'gcc' failed with exit status 1
running install
running bdist_egg
running egg_info
writing resample2d_cuda.egg-info/PKG-INFO
writing dependency_links to resample2d_cuda.egg-info/dependency_links.txt
writing top-level names to resample2d_cuda.egg-info/top_level.txt
reading manifest file 'resample2d_cuda.egg-info/SOURCES.txt'
writing manifest file 'resample2d_cuda.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'resample2d_cuda' extension
gcc -pthread -B /media/data2/xly/anaconda3/envs/py36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/media/data2/xly/anaconda3/envs/py36/lib/python3.6/site-packages/torch/lib/include -I/media/data2/xly/anaconda3/envs/py36/lib/python3.6/site-packages/torch/lib/include/TH -I/media/data2/xly/anaconda3/envs/py36/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/media/data2/xly/anaconda3/envs/py36/include/python3.6m -c resample2d_cuda.cc -o build/temp.linux-x86_64-3.6/resample2d_cuda.o -std=c++11 -DTORCH_EXTENSION_NAME=resample2d_cuda
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda/bin/nvcc -I/media/data2/xly/anaconda3/envs/py36/lib/python3.6/site-packages/torch/lib/include -I/media/data2/xly/anaconda3/envs/py36/lib/python3.6/site-packages/torch/lib/include/TH -I/media/data2/xly/anaconda3/envs/py36/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/media/data2/xly/anaconda3/envs/py36/include/python3.6m -c resample2d_kernel.cu -o build/temp.linux-x86_64-3.6/resample2d_kernel.o -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -DTORCH_EXTENSION_NAME=resample2d_cuda --compiler-options '-fPIC' -std=c++11
resample2d_kernel.cu:3:35: fatal error: ATen/cuda/CUDAContext.h: No such file or directory
 #include <ATen/cuda/CUDAContext.h>
                                   ^
compilation terminated.
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
running install
running bdist_egg
running egg_info
writing channelnorm_cuda.egg-info/PKG-INFO
writing dependency_links to channelnorm_cuda.egg-info/dependency_links.txt
writing top-level names to channelnorm_cuda.egg-info/top_level.txt
reading manifest file 'channelnorm_cuda.egg-info/SOURCES.txt'
writing manifest file 'channelnorm_cuda.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'channelnorm_cuda' extension
gcc -pthread -B /media/data2/xly/anaconda3/envs/py36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/media/data2/xly/anaconda3/envs/py36/lib/python3.6/site-packages/torch/lib/include -I/media/data2/xly/anaconda3/envs/py36/lib/python3.6/site-packages/torch/lib/include/TH -I/media/data2/xly/anaconda3/envs/py36/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/media/data2/xly/anaconda3/envs/py36/include/python3.6m -c channelnorm_cuda.cc -o build/temp.linux-x86_64-3.6/channelnorm_cuda.o -std=c++11 -DTORCH_EXTENSION_NAME=channelnorm_cuda
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda/bin/nvcc -I/media/data2/xly/anaconda3/envs/py36/lib/python3.6/site-packages/torch/lib/include -I/media/data2/xly/anaconda3/envs/py36/lib/python3.6/site-packages/torch/lib/include/TH -I/media/data2/xly/anaconda3/envs/py36/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/media/data2/xly/anaconda3/envs/py36/include/python3.6m -c channelnorm_kernel.cu -o build/temp.linux-x86_64-3.6/channelnorm_kernel.o -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -DTORCH_EXTENSION_NAME=channelnorm_cuda --compiler-options '-fPIC' -std=c++11
channelnorm_kernel.cu:3:35: fatal error: ATen/cuda/CUDAContext.h: No such file or directory
 #include <ATen/cuda/CUDAContext.h>
                                   ^
compilation terminated.
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

**Comment by Zhuysheng** [comment]
@xuleyoung  i meet the same question, how to solve it

**Comment by osamagharbi** [comment]
@xuleyoung @Zhuysheng did you find the solution ?

**Comment by Zhuysheng** [comment]
@osamagharbi  maybe you can try pytorch version 1.0.0, it solved my problem.

**Comment by wellsweiwei** [comment]
> @osamagharbi maybe you can try pytorch version 1.0.0, it solved my problem.

but it gives another error: 

running install
running bdist_egg
running egg_info
writing channelnorm_cuda.egg-info/PKG-INFO
writing dependency_links to channelnorm_cuda.egg-info/dependency_links.txt
writing top-level names to channelnorm_cuda.egg-info/top_level.txt
reading manifest file 'channelnorm_cuda.egg-info/SOURCES.txt'
writing manifest file 'channelnorm_cuda.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'channelnorm_cuda' extension
gcc -pthread -B /home/messor/users/weiwei/anaconda3/envs/vid2vid/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/messor/users/weiwei/anaconda3/envs/vid2vid/lib/python3.6/site-packages/torch/lib/include -I/home/messor/users/weiwei/anaconda3/envs/vid2vid/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/messor/users/weiwei/anaconda3/envs/vid2vid/lib/python3.6/site-packages/torch/lib/include/TH -I/home/messor/users/weiwei/anaconda3/envs/vid2vid/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda-9.0/include -I/usr/local/cuda-9.0/lib64/libcudnn.so.7/include -I/home/messor/users/weiwei/anaconda3/envs/vid2vid/include/python3.6m -c channelnorm_cuda.cc -o build/temp.linux-x86_64-3.6/channelnorm_cuda.o -std=c++11 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=channelnorm_cuda -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: error: /usr/local/cuda-9.0/lib64/libcudnn.so.7/include: Not a directory
error: command 'gcc' failed with exit status 1

I don't know why this path "/usr/local/cuda-9.0/lib64/libcudnn.so.7/include" will be given, where to change it?

**Comment by MohammedSaad18** [comment]
The Master branch now is working with 
cuda 10 
pytorch 1.0.0
GCC 7.4.0

**Comment by Jiangfeng-Xiong** [comment]
pytorch 1.0.0 is ok, while pytorch0.4.1 does not work

**Comment by jjkislele** [comment]
- [ ] pytorch 0.4.1, cuda 8/9 **nope**
- [x] pytorch 1.0.0, cuda 10 **works**
- [ ] pytorch 1.0.1, cuda 10 **nope**

**Comment by CJEQ** [comment]
pytorch 1.1.0, cuda 10, python 27 works

**Comment by stitchy1** [comment]
I upgraded my pytorch version to 1.3.0, recompiled successfully and come up to the ImportError when train:

Traceback (most recent call last):
  File "main.py", line 19, in <module>
    import models, losses, datasets
  File "/home/jcy/flownet2-pytorch/models.py", line 8, in <module>
    from networks.resample2d_package.resample2d import Resample2d
  File "/home/jcy/flownet2-pytorch/networks/resample2d_package/resample2d.py", line 3, in <module>
    import resample2d_cuda
ImportError: /home/jcy/.local/lib/python3.6/site-packages/resample2d_cuda-0.0.0-py3.6-linux-x86_64.egg/resample2d_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1011CPUTensorIdEv

Does anyone meet the same problem?
How to modify the codes to make pytorch 1.3.0, cuda 10, python 3.6 work?

**Comment by zhuixunforever** [comment]
pytorch 1.0.0, cuda 9.0, python 3.6 works

**Comment by thohemp** [comment]
Had the same issue.
cuda 10
pytorch 1.0.0
GCC 7.4.0

Changing cuda with https://github.com/phohenecker/switch-cuda/blob/master/switch-cuda.sh

**Comment by YuesongNan** [comment]
pytorch 1.3.1, cuda 10, python 36 **nopes**

**Comment by cgokce** [comment]
Ubuntu 16.04 - Driver: 440.33

- [ ] pytorch 0.4.1, cuda 10.2, python 36 **nopes**
- [ ] pytorch 1.0.1, cuda 10.2, python 36 **nopes**
- [x] pytorch 1.4.0, cuda 10.2, python 36 **works**

**Comment by YangLiu14** [comment]
pytorch 1.0.0, CUDA 9.0, gcc=5.3.1, g++=5.3.1  **works**

**Comment by zhmeishi** [comment]
pytorch 1.1.0, CUDA 9.0, gcc=5.3.1, g++=5.3.1 works

**Comment by Queenyy** [comment]
@cgokce @jjkislele Hi, I use pytorch1.0.0 Cuda10.0, it works. 
But when i train FlowNet2C, the loss is bumping, while training FlowNet2S the loss can decrease. Is this due to the correlation layer or pytorch version which isn't the same as the repo? Did you train FlowNet2 successfully? could you please give me some suggestions, thanks very much.

**Comment by ChriisYoung** [comment]
python3.6-cuda9.0-cudnn7.6-pytorch0.4.1-gcc5.5.0  nopes

**Comment by chaoxingxi** [comment]
pytorch 1.4.0, cuda 10.1, python 36 works

**Comment by mayujie** [comment]
- nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04
- gcc-7 g++-7
- python3.6
- pip3
- `pip3 install torch==1.0.0 -f https://download.pytorch.org/whl/cu90/torch_stable.html`

works for me! :)

**Comment by sfstefanwu** [comment]
ubuntu 18.04, python 3.6, torch 1.0.0, cuda 9.0 works for me.

**Comment by chaoxingxi** [comment]
您发给我的信件已经收到，我会尽快给您答复！                         ---------------- 席超星

**Comment by BenMaslen** [comment]
python 3.9 pytorch 1.1 cuda 11.2 - FAILS
python 3.7 pytorch 0.4.1 cuda 10 - FAILS
python 3.7 pytorch 0.4.1 cuda 11.1 - FAILS
python 3.7 pytorch 0.4.1 cuda 11.2 - FAILS
python 3.9 pytorch 1.8 cuda 11.2 - FAILS
python 3.9 pytorch 1.9 cuda 11.2 - FAILS
python 3.9 pytorch 1.1 cuda 10.0.13 - FAILS
python 3.7 pytorch 0.4.1 cuda 10.0.13 - FAILS
python 3.7 pytorch 0.4.1 cuda 10.2 - FAILS
python 3.7 pytorch 0.4.1 cuda 11.1 - FAILS
python 3.7 pytorch 0.4.1 cuda 11.2 - FAILS
python 3.7 pytorch 0.4.1 cuda 11.3 - FAILS
python 3.7 pytorch 0.4.1 cuda 11.4 - FAILS
python 3.7 pytorch 1.1 cuda 10.0.13 - WORKS FINALLY!!!

**Comment by chaoxingxi** [comment]
您发给我的信件已经收到，我会尽快给您答复！                         ---------------- 席超星

**Comment by BeauDing** [comment]
In ubuntu 20.04,  perform command:

- conda install pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=10.0 -c pytorch

It works for me :)

**Comment by chaoxingxi** [comment]
您发给我的信件已经收到，我会尽快给您答复！                         ---------------- 席超星

**Comment by stha-prashant** [comment]
> o my god!!! ubuntu 20.04 python 3.6 cuda 10.0 gcc-7 words,works,works! The import thing repeat threee times!

hi what did you use for pytorch version?

**Comment by caidhome** [comment]
> > o my god!!! ubuntu 20.04 python 3.6 cuda 10.0 gcc-7 words,works,works! The import thing repeat threee times!
> 
> hi what did you use for pytorch version?

**conda install pytorch==1.2.0 torchvision==0.4.0 -c pytorch**
you try it!

**Comment by xiaoshijuejue** [comment]
你好，请问如果我没有权限访问下载FlowNet2_checkpoint.pth.tar的话，是否能使用其他的FlowNet2预载模型？
