### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by seehidre** [NVIDIA/flownet2-pytorch#163]
Hello, everyone. Have anybody ever encountered this problems below?How can I solve it???

Traceback (most recent call last):
  File "main.py", line 139, in <module>
    train_dataset = args.training_dataset_class(args, True, **tools.kwargs_from_args(args, 'training_dataset'))
  File "/home/lijian/flownet2-pytorch/datasets.py", line 112, in __init__
    super(MpiSintelFinal, self).__init__(args, is_cropped = is_cropped, root = root, dstype = 'final', replicates = replicates)
  File "/home/lijian/flownet2-pytorch/datasets.py", line 66, in __init__
    self.frame_size = frame_utils.read_gen(self.image_list[0][0]).shape
IndexError: list index out of range

**Comment by mathieumb** [comment]
As far as I could read the MPISintel dataloader will not work on the test set as it is, since it starts by searching for the ground truth files and there are none for the test set.

Also you must pass the root of the entire dataset, not just a sequence.

Try with ` --training_dataset_root /home/seehidre/flownet2-pytorch/MPI-Sintel-testing/training `

**Comment by leeeeeeo** [comment]
python main.py
--inference
--model FlowNet2
--save_flow
--save ./output
--inference_dataset ImagesFromFolder
--inference_dataset_root ./data/MPI-Sintel-testing/test/clean/wall
--resume ./models/FlowNet2_checkpoint.pth.tar

Try this!

**Comment by ryannggy** [comment]
i run into this same rror when i'm trying to run training on my own image set, is there any way to run training on your own dataset?

**Comment by Tranks27** [comment]
> i run into this same rror when i'm trying to run training on my own image set, is there any way to run training on your own dataset?

I'm trying to do the same for my own dataset. Did you figure it out?

**Comment by ryannggy** [comment]
hi there, you simply have to make sure that the directories are in the correct order, and /or you have the right dependencies installed.

otherwise, try using this one for inference, it works alright for inference (https://github.com/Gauravv97/flownet2-Colab)

> > i run into this same rror when i'm trying to run training on my own image set, is there any way to run training on your own dataset?
> 
> I'm trying to do the same for my own dataset. Did you figure it out?

**Comment by poincarelee** [comment]
@ryannggy  
Hi, could you tell me what "ImagesFromFolder " in the argument"--inference_dataset ImagesFromFolder "  means? after running the command, 12 .flo files are generated in the inference folder, but when changed to sintel/clean/tiger, still 12 .flo files generated,  what does these 12 files mean?
