### ISSUE TITLE
RuntimeError: function Resample2dFunctionBackward returned an incorrect number of gradients (expected 4, got 3)

### ISSUE THREAD

**Issue by TyroneLi** [NVIDIA/flownet2-pytorch#164]
Hi~I tried to train flownet2 using MPI-Sintel dataset,but I got such errors and can't make it.
My env is:
cuda10   pytorch1.1.0  python3  ubuntu18
And I had successfully done inference using model provided by author.
Somebody knows how to fix it?
`Traceback (most recent call last):: 89.164, load: 4.4e-05: 100%|#| 130/130.0 [00:11<00:00, 12.37it/s]
  File "main.py", line 426, in <module>t]
    train_loss, iterations = train(args=args, epoch=epoch, start_iteration=global_iteration, data_loader=train_loader, model=model_and_loss, optimizer=optimizer, logger=train_logger, offset=offset)
  File "main.py", line 292, in train
    loss_val.backward()
  File "/home/lijinlong/anaconda3/envs/flownet/lib/python3.6/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/lijinlong/anaconda3/envs/flownet/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: function Resample2dFunctionBackward returned an incorrect number of gradients (expected 4, got 3)
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/lijinlong/anaconda3/envs/flownet/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/lijinlong/anaconda3/envs/flownet/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lijinlong/anaconda3/envs/flownet/lib/python3.6/site-packages/torch/utils/data/_utils/pin_memory.py", line 21, in _pin_memory_loop
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/home/lijinlong/anaconda3/envs/flownet/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/lijinlong/anaconda3/envs/flownet/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 276, in rebuild_storage_fd
    fd = df.detach()
  File "/home/lijinlong/anaconda3/envs/flownet/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/lijinlong/anaconda3/envs/flownet/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/lijinlong/anaconda3/envs/flownet/lib/python3.6/multiprocessing/connection.py", line 493, in Client
    answer_challenge(c, authkey)
  File "/home/lijinlong/anaconda3/envs/flownet/lib/python3.6/multiprocessing/connection.py", line 732, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/home/lijinlong/anaconda3/envs/flownet/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/lijinlong/anaconda3/envs/flownet/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/lijinlong/anaconda3/envs/flownet/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer`

**Comment by vegnesh** [comment]
Facing the same issue

**Comment by TyroneLi** [comment]
> Facing the same issue.
> 
> Edit:
> 
> In `networks/resample2d_package/resample2d.py` , i edited the following line
> 
> `return grad_input1, grad_input2, None, None`
> 
> This changes the output dimension to 4. Not sure if it will call any training problems downstream

@vegnesh hi,I follow your suggestion and then train MpinSintel dataset.But during training,I got such error and everything dumpped.
`Overall Progress:   0%|                                                   | 0/10000 [00:00<?, ?it/s]THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument                                 | 0/65.0 [00:00<?, ?it/s]
/home/lijinlong/anaconda3/envs/pytorch_seg/lib/python3.6/site-packages/torch/nn/functional.py:2539: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
/home/lijinlong/anaconda3/envs/pytorch_seg/lib/python3.6/site-packages/torch/nn/parallel/_functions.py:61: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
Overall Progress:   0%|                                      | 20/10000 [17:00<134:57:05, 48.68s/it]                                         Warning: NaN or Inf found in input tensor. EPE: 61.507, load: 4.4e-05: 100%|██| 65/65.0 [00:19<00:00,  5.00it/s]
Warning: NaN or Inf found in input tensor.
Traceback (most recent call last):2.714, lr: 1.0e-04, load: 2.9e-05: 100%|████████████| 65/65.0 [00:44<00:00,  1.51it/s]
  File "main.py", line 426, in <module>, lr: 1.0e-04, load: 3.4e-05: 100%|████████████| 65/65.0 [00:44<00:00,  1.50it/s]
    train_loss, iterations = train(args=args, epoch=epoch, start_iteration=global_iteration, data_loader=train_loader, model=model_and_loss, optimizer=optimizer, logger=train_logger, offset=offset) 1.0e-04, load: 1.3e-04: 100%|████████████| 65/65.0 [00:44<00:00,  1.51it/s]
  File "main.py", line 325, in train30, lr: 1.0e-04, load: 5.0e-05: 100%|█████████████| 65/65.0 [00:44<00:00,  1.49it/s]
    logger.add_histogram(str(key), all_losses[:, i], global_iteration)/65.0 [00:14<00:00,  4.97it/s]
  File "/home/lijinlong/anaconda3/envs/pytorch_seg/lib/python3.6/site-packages/tensorboardX/writer.py", line 443, in add_histogram
    histogram(tag, values, bins, max_bins=max_bins), global_step, walltime)███████████| 65/65.0 [00:44<00:00,  1.49it/s]
  File "/home/lijinlong/anaconda3/envs/pytorch_seg/lib/python3.6/site-packages/tensorboardX/summary.py", line 138, in histogram
    hist = make_histogram(values.astype(float), bins, max_bins)1e-05: 100%|███████████| 65/65.0 [00:45<00:00,  1.49it/s]
  File "/home/lijinlong/anaconda3/envs/pytorch_seg/lib/python3.6/site-packages/tensorboardX/summary.py", line 176, in make_histogram
    raise ValueError('The histogram is empty, please file a bug report.')%|███████████| 65/65.0 [00:44<00:00,  1.49it/s]
ValueError: The histogram is empty, please file a bug report.00%|█| 65/65.0 [00:15<00:00,  4.98it/s]`

**Comment by vegnesh** [comment]
Same issue for me as well, but not in the first iteration

**Comment by fitsumreda** [comment]
thanks, we are looking into this bug. In the meanwhile, you can revert to version that should resolve the current Resample2D related error. 
https://github.com/NVIDIA/flownet2-pytorch/tree/5ea2f10e7a225c11edcdae8f789fd530604aef42

**Comment by fitsumreda** [comment]
this has been fixed now.

**Comment by kashyap92** [comment]
@TyroneLi , Hello! I recently tried to train the network and am stuck with the same error "raise ValueError('The histogram is empty, please file a bug report.)". How did you fix it?

**Comment by kartheekmedathati** [comment]
I am facing the same issue, could you please share the fix?

**Comment by ChenjieWang** [comment]
> this has been fixed now.

Hello, I encountered the bug “ValueError: The histogram is empty, please file a bug report.".  Do you have a solution?

**Comment by ChenjieWang** [comment]
> this has been fixed now.

@fitsumreda Hello, I encountered the bug “ValueError: The histogram is empty, please file a bug report.". Do you have a solution?

**Comment by AjithPanja** [comment]
@ChenjieWang @kartheekmedathati Any solution to this issue ?
