### ISSUE TITLE
[Bug Report] This is a bug in correlation module when kernel_size > 1

### ISSUE THREAD

**Issue by EthanZhangYi** [NVIDIA/flownet2-pytorch#167]
In coorelation module, the output size is determined by
https://github.com/NVIDIA/flownet2-pytorch/blob/71034046166735a79a5b82df78de72d806e82842/networks/correlation_package/correlation_cuda.cc#L33-L34
Thus there is a bug in `correlation_cuda_kernel.cu`
https://github.com/NVIDIA/flownet2-pytorch/blob/71034046166735a79a5b82df78de72d806e82842/networks/correlation_package/correlation_cuda_kernel.cu#L90-L91
It should be
```
int32_t y1 = blockIdx.y * stride1 + max_displacement + kernel_rad;
int32_t x1 = blockIdx.z * stride1 + max_displacement + kernel_rad;
```
When `kernel_size=1`, `kernel_rad=0`, no bug occurs in `FlowNetC`.
However, when `kernel_size>1`,  an error in #128 will be raised.

Please fix this bug, `backward` kernels may need to be fixed as well.

**Comment by nbei** [comment]
This bug will cause the cuda runtime errorL: illegal memory access was encountered. 
If you just run this code in pytorch1.0 and cuda9.0, the kernel can work well in the first several iteration like below:
[2019-08-07 00:49:28,949 INFO lgdnet.py line 308 368536] 
 test-error Rank[0] Iter [23/300000.0] 
 { 'time_data': 0.5301296710968018, 'time_infer': 1.6038336753845215}
Traceback (most recent call last):
  File "tools/train.py", line 165, in <module>
    main()
  File "tools/train.py", line 149, in main
    lgd_res, initial_res = lgd_model.optimizer_parameters(input_dict)
  File "/home/xxx/pytorch_project/LGDNet/models/lgdnet.py", line 96, in optimizer_parameters
    self.loss_total.backward()
  File "/data0/xxx/anaconda3/envs/pytorch-1.1/lib/python3.6/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/data0/xxx/anaconda3/envs/pytorch-1.1/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered (insert_events at /opt/conda/conda-bld/pytorch_1556653183467/work/c10/cuda/CUDACachingAllocator.cpp:564)

However, if you are using cuda10 and pytorch1.1, the correlation kernel cannot work anymore.

**Comment by wuzht** [comment]
@EthanZhangYi  I got this error when `kernel_size > 1`, do you have any idea how can I fix this problem? Thanks.
