### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by DangerousY** [NVIDIA/flownet2-pytorch#174]
Traceback (most recent call last):
  File "train.py", line 148, in <module>
    train()
  File "train.py", line 28, in train
    models = create_model(opt)
  File "/home/zyx/vid2vid/models/models.py", line 79, in create_model
    flowNet.initialize(opt)        
  File "/home/zyx/vid2vid/models/flownet.py", line 14, in initialize
    from .flownet2_pytorch import models as flownet2_models
  File "/home/zyx/vid2vid/models/flownet2_pytorch/models.py", line 8, in <module>
    from .networks.resample2d_package.resample2d import Resample2d
  File "/home/zyx/vid2vid/models/flownet2_pytorch/networks/resample2d_package/resample2d.py", line 3, in <module>
    import resample2d_cuda
ImportError: /home/zyx/.local/lib/python3.6/site-packages/resample2d_cuda-0.0.0-py3.6-linux-x86_64.egg/resample2d_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE

**Comment by DangerousY** [comment]
When your pytorch's version isn't compatible with your CUDA'version, the problem will exist.
