### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ucasfhx** [NVIDIA/flownet2-pytorch#182]
I used this command :
python main.py --inference --model FlowNet2 --save_flow --inference_dataset MpiSintelClean --inference_dataset_root /data/fanhongxing/env-flownet2/flownet2-pytorch/MPI-Sintel-complete/test/ --resume /data/fanhongxing/env-flownet2/flownet2-pytorch/checkpoints/FlowNet2_checkpoint.pth.tar

But something went wrong,
Parsing Arguments
  [8.570s] batch_size: 8
  [8.570s] crop_size: [256, 256]
  [8.570s] fp16: False
  [8.570s] fp16_scale: 1024.0
  [8.570s] gradient_clip: None
  [8.570s] inference: True
  [8.570s] inference_batch_size: 1
  [8.570s] inference_dataset: MpiSintelClean
  [8.570s] inference_dataset_replicates: 1
  [8.570s] inference_dataset_root: /data/fanhongxing/env-flownet2/flownet2-pytorch/MPI-Sintel-complete/test/
  [8.570s] inference_n_batches: -1
  [8.570s] inference_size: [-1, -1]
  [8.570s] log_frequency: 1
  [8.570s] loss: L1Loss
  [8.570s] model: FlowNet2
  [8.570s] model_batchNorm: False
  [8.570s] model_div_flow: 20.0
  [8.570s] name: run
  [8.570s] no_cuda: False
  [8.570s] number_gpus: 10
  [8.570s] number_workers: 8
  [8.570s] optimizer: Adam
  [8.570s] optimizer_amsgrad: False
  [8.570s] optimizer_betas: (0.9, 0.999)
  [8.570s] optimizer_eps: 1e-08
  [8.570s] optimizer_lr: 0.001
  [8.570s] optimizer_weight_decay: 0
  [8.570s] render_validation: False
  [8.570s] resume: /data/fanhongxing/env-flownet2/flownet2-pytorch/checkpoints/FlowNet2_checkpoint.pth.tar
  [8.570s] rgb_max: 255.0
  [8.570s] save: ./work
  [8.570s] save_flow: True
  [8.570s] schedule_lr_fraction: 10
  [8.570s] schedule_lr_frequency: 0
  [8.570s] seed: 1
  [8.570s] skip_training: False
  [8.570s] skip_validation: False
  [8.570s] start_epoch: 1
  [8.570s] total_epochs: 10000
  [8.570s] train_n_batches: -1
  [8.570s] training_dataset: MpiSintelFinal
  [8.570s] training_dataset_replicates: 1
  [8.570s] training_dataset_root: ./MPI-Sintel/flow/training
  [8.570s] validation_dataset: MpiSintelClean
  [8.570s] validation_dataset_replicates: 1
  [8.570s] validation_dataset_root: ./MPI-Sintel/flow/training
  [8.570s] validation_frequency: 5
  [8.570s] validation_n_batches: -1
  [8.580s] Operation finished

Source Code
  Current Git Hash: b'71034046166735a79a5b82df78de72d806e82842'

Initializing Datasets
  [0.010s] Operation failed  

**Traceback (most recent call last):
  File "main.py", line 153, in <module>
    inference_dataset = args.inference_dataset_class(args, False, **tools.kwargs_from_args(args, 'inference_dataset'))
  File "/data/fanhongxing/env-flownet2/flownet2-pytorch/datasets.py", line 108, in __init__
    super(MpiSintelClean, self).__init__(args, is_cropped = is_cropped, root = root, dstype = 'clean', replicates = replicates)
  File "/data/fanhongxing/env-flownet2/flownet2-pytorch/datasets.py", line 66, in __init__
    self.frame_size = frame_utils.read_gen(self.image_list[0][0]).shape
IndexError: list index out of range**

How can I solve this issue?

**Comment by leeeeeeo** [comment]
python main.py
--inference
--model FlowNet2
--save_flow
--save ./output
--inference_dataset ImagesFromFolder
--inference_dataset_root ./data/MPI-Sintel-testing/test/clean/wall
--resume ./models/FlowNet2_checkpoint.pth.tar

Try this!

**Comment by LiUzHiAn** [comment]
@ucasfhx ,
At first, I met the same issue with you. I found this is caused by the extensions of images. 
Specifically, the constructor param `iext` is set to be `png` as default in `ImageFromFolder` class.

So, you can either modify this param or change you images' format. :smile:

**Comment by ucasfhx** [comment]
> python main.py
> --inference
> --model FlowNet2
> --save_flow
> --save ./output
> --inference_dataset ImagesFromFolder
> --inference_dataset_root ./data/MPI-Sintel-testing/test/clean/wall
> --resume ./models/FlowNet2_checkpoint.pth.tar
> 
> Try this!

Thanks! I have solved this problem

**Comment by ucasfhx** [comment]
> @ucasfhx ,
> At first, I met the same issue with you. I found this is caused by the extensions of images.
> Specifically, the constructor param `iext` is set to be `png` as default in `ImageFromFolder` class.
> 
> So, you can either modify this param or change you images' format. 😄

Thanks! I had a problem with my version of GCC, which was eventually fixed.

**Comment by izhimahu** [comment]
Can you tell me how you solved it?I have the same problem

**Comment by Byh294249** [comment]
> > @ucasfhx ,
> > At first, I met the same issue with you. I found this is caused by the extensions of images.
> > Specifically, the constructor param `iext` is set to be `png` as default in `ImageFromFolder` class.
> > So, you can either modify this param or change you images' format. 😄
> 
> Thanks! I had a problem with my version of GCC, which was eventually fixed.

hello，could you tell me what's wrong with your version GCC, i met the same issue.
