### ISSUE TITLE
run run_a_pair.py error

### ISSUE THREAD

**Issue by semchan** [NVIDIA/flownet2-pytorch#198]
Dear,

I just modified the input images as mine for .jpg as the size are 1280*720, but got the below error. 
how can I fix it? thanks  a lot.

/pytorch/torch/csrc/autograd/python_function.cpp:622: UserWarning: Legacy autograd function with non-static forward method is deprecated and will be removed in 1.3. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)
Traceback (most recent call last):
  File "run_a_pair.py", line 38, in <module>
    result = net(im).squeeze()
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/sem/NDT/VisualTracking/flownet2-pytorch/models.py", line 139, in forward
    flownetc_flow2 = self.flownetc(x)[0]
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/sem/NDT/VisualTracking/flownet2-pytorch/networks/FlowNetC.py", line 106, in forward
    concat5 = torch.cat((out_conv5,out_deconv5,flow6_up),1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 16 and 15 in dimension 3 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:71

**Comment by lhao0301** [comment]
Try to resize the image so that it can be divided by 64. The problem occurs because of the misalignment within the network(conv, deconv).

**Comment by semchan** [comment]
noted with thanks






Best Regards
 陈尧森，Sem Chan
Tel: 15208489326


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hao Luo"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月17日(星期一) 中午11:17
收件人:&nbsp;"NVIDIA/flownet2-pytorch"<flownet2-pytorch@noreply.github.com&gt;;
抄送:&nbsp;"Sem chan"<380003859@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [NVIDIA/flownet2-pytorch] run run_a_pair.py error (#198)




Try to resize the image so that it can be divided by 64. The problem occurs because of the misalignment within the network(conv, deconv).

**Comment by birdflyto** [comment]
Thanks for your answer



---Original---

**Comment by fanbooo** [comment]
any solution?
