### ISSUE TITLE
CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

### ISSUE THREAD

**Issue by alizezhu** [NVIDIA/flownet2-pytorch#218]
When I install by "bash install.sh", I got the error 

Traceback (most recent call last):
  File "setup.py", line 24, in <module>
    ], extra_compile_args={'cxx': cxx_args, 'nvcc': nvcc_args})
  File "/home/user/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 498, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "/home/user/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 577, in library_paths
    if (not os.path.exists(_join_cuda_home(lib_dir)) and
  File "/home/user/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1252, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '

OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

Anyone had the same problem? I searched online but still could not fix it. Any tips what to do? Thanks in advance!

**Comment by waseemshariff126** [comment]
I am getting the same error. Did you get the solution ?

**Comment by 1187697147** [comment]
Hi, I think you should set CUDA_HOME, you can see it in /usr/local/cuda....
If not, please re-install CUDA. I have met this situation many times, it will be ok using above methods.
Gook luck.

**Comment by BranchScope** [comment]
> Hi, I think you should set CUDA_HOME, you can see it in /usr/local/cuda....
> If not, please re-install CUDA. I have met this situation many times, it will be ok using above methods.
> Gook luck.

Hi, i'm on Arch Linux and there is no any path of cuda in `/usr/*`, there are just `/usr/local/include/c10/cuda` and `/opt/cuda`.
Anyway even if i set `CUDA_HOME` on these path the build.sh still not working for the same error.

**Comment by eyabesbes** [comment]
> Hi, I think you should set CUDA_HOME, you can see it in /usr/local/cuda.... If not, please re-install CUDA. I have met this situation many times, it will be ok using above methods. Gook luck.

Hi, I am working on anaconda on windows 11. I have installed cudatoolkit with pip and I'm encountering the same problem do you have any idea how can I solve that ?
