### ISSUE TITLE
unexpected keyword argument 'fp16'

### ISSUE THREAD

**Issue by karims** [NVIDIA/flownet2-pytorch#233]
I am usinf flownet from inside vid2vid. I get this following error. Any idea how to resolve this? Using with `docker, Ubuntu 16, pytorch 1.0.0`

Traceback (most recent call last):
  File "train.py", line 149, in <module>
    train()
  File "train.py", line 28, in train
    models = create_model(opt)
  File "/vid2vid/models/models.py", line 83, in create_model
    flowNet.initialize(opt)
  File "/vid2vid/models/flownet.py", line 18, in initialize
    self.flowNet = flownet2_tools.module_to_dict(flownet2_models)['FlowNet2'](fp16=opt.fp16).cuda(self.gpu_ids[0])        
TypeError: __init__() got an unexpected keyword argument 'fp16'

**Comment by moulimatsa** [comment]
@karims I have the same issue. Were you able to resolve the issue.

**Comment by zhangbowen1999** [comment]
@karims I have the same issue. Were you able to resolve the issue

**Comment by zhangbowen1999** [comment]
> @karims I have the same issue. Were you able to resolve the issue.

Excuse me. Have you solved it yet

**Comment by zhangbowen1999** [comment]
> I am usinf flownet from inside vid2vid. I get this following error. Any idea how to resolve this? Using with `docker, Ubuntu 16, pytorch 1.0.0`
> 
> ```
> Traceback (most recent call last):
>   File "train.py", line 149, in <module>
>     train()
>   File "train.py", line 28, in train
>     models = create_model(opt)
>   File "/vid2vid/models/models.py", line 83, in create_model
>     flowNet.initialize(opt)
>   File "/vid2vid/models/flownet.py", line 18, in initialize
>     self.flowNet = flownet2_tools.module_to_dict(flownet2_models)['FlowNet2'](fp16=opt.fp16).cuda(self.gpu_ids[0])        
> TypeError: __init__() got an unexpected keyword argument 'fp16'
> ```

Excuse me. Have you solved it yet

**Comment by UE-algo104** [comment]
runner.train(
    # engine=dl.CPUEngine(),  # for simplicity reasons, let's run everything on cpu
    engine=dl.GPUEngine("cuda:0"),       #< add use GPUEngine
    model=model,
    criterion=criterion,

**Comment by MohammadRezaG** [comment]
> engine=dl.GPUEngine("cuda:0"),

Thanks
