### ISSUE TITLE
ValueError (inference)

### ISSUE THREAD

**Issue by lineker10** [NVIDIA/flownet2-pytorch#265]
Hello.
I cannot solve this error when inference Example on MPISintel Clean
My error message is as follows.

=======================================
Traceback (most recent call last):
  File "main.py", line 68, in <module>
    tools.add_arguments_for_module(parser, torch.optim, argument_for_class='optimizer', default='Adam', skip_params=['params'])
  File "/home/yspark/Down/flownet2-pytorch/utils/tools.py", line 64, in add_arguments_for_module
    argspec = inspect.getargspec(class_obj.__init__)
  File "/usr/lib/python3.8/inspect.py", line 1095, in getargspec
    raise ValueError("Function has keyword-only parameters or annotations"
ValueError: Function has keyword-only parameters or annotations, use inspect.signature() API which can support them
==========================================
Please, help me
Good bye and good luck to you

**Comment by b06901089** [comment]
change 
inspect.getargspec 
to 
inspect.getfullargspec
