### ISSUE TITLE
error in Correlation_forward_cuda_kernel: invalid device function

### ISSUE THREAD

**Issue by erickwan** [NVIDIA/flownet2-pytorch#33]
When I tried to run `python main.py` for inference, I got the following error

```
Overall Progress:   0%|                                                       | 0/1 [00:00<?, ?it/s]error in Correlation_forward_cuda_kernel: invalid device functionncing :   0%|                                                         | 0/1.0 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 397, in <module>
    stats = inference(args=args, epoch=epoch - 1, data_loader=inference_loader, model=model_and_loss, offset=offset)
  File "main.py", line 361, in inference
    losses, output = model(data[0], target[0], inference=True)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 66, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "main.py", line 165, in forward
    output = self.model(data)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ekwan/flownet2-pytorch/models.py", line 118, in forward
    flownetc_flow2 = self.flownetc(x)[0]
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ekwan/flownet2-pytorch/networks/FlowNetC.py", line 86, in forward
    out_corr = self.corr(out_conv3a, out_conv3b) # False
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ekwan/flownet2-pytorch/networks/correlation_package/modules/correlation.py", line 17, in forward
    result = CorrelationFunction(self.pad_size, self.kernel_size, self.max_displacement,self.stride1, self.stride2, self.corr_multiply)(input1, input2)
  File "/home/ekwan/flownet2-pytorch/networks/correlation_package/functions/correlation.py", line 30, in forward
    self.pad_size, self.kernel_size, self.max_displacement,self.stride1, self.stride2, self.corr_multiply)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/__init__.py", line 180, in safe_call
    result = torch._C._safe_call(*args, **kwargs)
torch.FatalError: aborting at /home/ekwan/flownet2-pytorch/networks/correlation_package/src/correlation_cuda.c:88
```

Turns out in the 3 `make.sh`, the architecture is hardcoded to `-arch=sm_52` and in my case it needs to be `-arch=sm_37`.   It's probably a good idea to update the documentation to save people time from troubleshooting.

**Comment by fitsumreda** [comment]
Thanks @erickwan . We will make that script compatible with multiple archs.

**Comment by smallmango** [comment]
i meet the same error, and i change the arch=sm_, it can not be solved also.
