### ISSUE TITLE
ImportError: /flownet2-pytorch/networks/resample2d_package/_ext/resample2d/_resample2d.so: undefined symbol: _Py_Dealloc

### ISSUE THREAD

**Issue by p31415926** [NVIDIA/flownet2-pytorch#36]
root@c38c6ed6d9fa:/flownet2-pytorch# python main.py --help
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    import models, losses, datasets
  File "/flownet2-pytorch/models.py", line 8, in <module>
    from networks.resample2d_package.modules.resample2d import Resample2d
  File "/flownet2-pytorch/networks/resample2d_package/modules/resample2d.py", line 3, in <module>
    from ..functions.resample2d import Resample2dFunction
  File "/flownet2-pytorch/networks/resample2d_package/functions/resample2d.py", line 3, in <module>
    from .._ext import resample2d
  File "/flownet2-pytorch/networks/resample2d_package/_ext/resample2d/__init__.py", line 3, in <module>
    from ._resample2d import lib as _lib, ffi as _ffi
ImportError: /flownet2-pytorch/networks/resample2d_package/_ext/resample2d/_resample2d.so: undefined symbol: _Py_Dealloc

**Comment by p31415926** [comment]
issue solved, in docker environment also need run install.sh

**Comment by fitsumreda** [comment]
Did you install the custom layers?
It would also help debug things if you give more details about the error.

**Comment by fitsumreda** [comment]
Ok, got it.

**Comment by sczhou** [comment]
@fitsumreda  Hi, I still have the error, though I install the these layers:
from .._ext import correlation
File "/flownet2-pytorch/networks/correlation_package/_ext/correlation/__init__.py", line 3, in <module>
from ._correlation import lib as _lib, ffi as _ffi
ImportError: /flownet2-pytorch/networks/correlation_package/_ext/correlation/_correlation.so: undefined symbol: PyInt_FromLong
