### ISSUE TITLE
Cannot run main.py properly

### ISSUE THREAD

**Issue by zengzhi2015** [NVIDIA/flownet2-pytorch#56]
I have successfully installed the docker image. However, I cannot even run the "python main.py --help". Could you please help me with this problem? Thanks!

```
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    import models, losses, datasets
  File "/flownet2-pytorch/models.py", line 8, in <module>
    from .networks.resample2d_package.modules.resample2d import Resample2d
ValueError: Attempted relative import in non-package
```

**Comment by fitsumreda** [comment]
Did you run install.shas described in the reader.It seems the custom layers have not been installed.
