### ISSUE TITLE
ImportError: networks/resample2d_package/_ext/resample2d/_resample2d.so: undefined symbol: state

### ISSUE THREAD

**Issue by HopLee6** [NVIDIA/flownet2-pytorch#64]
After running "bash install.sh" successfully, it reports an error when executing "import models".

 `opt602@opt602-All-Series:~/lhp/flownet2-pytorch-master$ python
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import models
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "models.py", line 8, in <module>
    from networks.resample2d_package.modules.resample2d import Resample2d
  File "networks/resample2d_package/modules/resample2d.py", line 3, in <module>
    from ..functions.resample2d import Resample2dFunction
  File "networks/resample2d_package/functions/resample2d.py", line 2, in <module>
    from .._ext import resample2d
  File "networks/resample2d_package/_ext/resample2d/__init__.py", line 3, in <module>
    from ._resample2d import lib as _lib, ffi as _ffi
ImportError: networks/resample2d_package/_ext/resample2d/_resample2d.so: undefined symbol: state
>>> 
`
Did I run "install.sh" unsuccessfully? Or did I miss some dependencies?

**Comment by HopLee6** [comment]
This problem has been solved by changing the version of pytorch to "0.2 post3". "0.2 post2" will lead to the problem.
