### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by kristinarakova** [NVIDIA/flownet2-pytorch#67]
I run your code  with command

python main.py --batch_size 1 --model FlowNet2C --optimizer=Adam --optimizer_lr=1e-4 --loss=MultiScale --loss_norm=L1 --loss_numScales=5 --loss_startScale=4 --optimizer_lr=1e-4 --crop_size 384 512 --training_dataset MpiSintelFinal --training_dataset_root ./home/kristina/Desktop/flownet2-pytorch/MPI-Sintel/training/final  --validation_dataset MpiSintelClean --validation_dataset_root /home/kristina/Desktop/flownet2-pytorch/MPI-Sintel/training/clean

and face with error:

Traceback (most recent call last):
  File "main.py", line 133, in <module>
    train_dataset = args.training_dataset_class(args, True, **tools.kwargs_from_args(args, 'training_dataset'))
  File "/home/kristina/Desktop/flownet2-pytorch/datasets.py", line 112, in __init__
    super(MpiSintelFinal, self).__init__(args, is_cropped = is_cropped, root = root, dstype = 'final', replicates = replicates)
  File "/home/kristina/Desktop/flownet2-pytorch/datasets.py", line 66, in __init__
    self.frame_size = frame_utils.read_gen(self.image_list[0][0]).shape
IndexError: list index out of range

Do you know what problem is?

**Comment by dustinfreeman** [comment]
I'm seeing the same.

    root@10c48a8434d3:/flownet2-pytorch# python main.py --inference --model FlowNet2 --save_flow --inference_dataset MpiSintelClean --inference_dataset_root /MPI-Sintel-complete/test/clean/cave_3/

Traceback (most recent call last):
  File "main.py", line 149, in <module>
    inference_dataset = args.inference_dataset_class(args, False, **tools.kwargs_from_args(args, 'inference_dataset'))
  File "/flownet2-pytorch/datasets.py", line 108, in __init__
    super(MpiSintelClean, self).__init__(args, is_cropped = is_cropped, root = root, dstype = 'clean', replicates = replicates)
  File "/flownet2-pytorch/datasets.py", line 66, in __init__
    self.frame_size = frame_utils.read_gen(self.image_list[0][0]).shape
IndexError: list index out of range

**Comment by seehidre** [comment]
Hi, I have encountered the same problem just like yours, did you solve it?? for dustinfreeman' reply,to be honest, I didn't understand totally.
