### ISSUE TITLE
flownet2-fine tune

### ISSUE THREAD

**Issue by qiuzhongwei-USTB** [NVIDIA/flownet2-pytorch#72]
how to fine tune flownet2 in pytorch?
python main.py --start_epoch 1 --total_epochs 10 --save ./work --batch_size 8 --model FlowNet2 --loss=L1Loss --optimizer=Adam --optimizer_lr=1e-10 \
--training_dataset MpiSintelFinal --training_dataset_root /home/data/flownet2_data/training/  \
--validation_dataset MpiSintelClean --validation_dataset_root /home/data/flownet2_data/training/ --resume /home/data/flownet2_data/pre-trained_model/FlowNet2_checkpoint.pth
this is the my code, how to solve this problem?
trhank you

**Comment by USTBQzw** [comment]
Overall Progress:   0%|                                                      | 0/11 [00:00<?, ?it/s]                    Traceback (most recent call last):
  File "main.py", line 417, in <module>                                                       | 0/131.0 [00:00<?, ?it/s]
    train_loss, iterations = train(args=args, epoch=epoch, start_iteration=global_iteration, data_loader=train_loader, model=model_and_loss, optimizer=optimizer, logger=train_logger, offset=offset)
  File "main.py", line 253, in train
    for batch_idx, (data, target) in enumerate(progress):
  File "/usr/local/lib/python2.7/dist-packages/tqdm/_tqdm.py", line 930, in __iter__
    for obj in iterable:
  File "/home/data/flownet2-pytorch-zw/utils/tools.py", line 111, in __next__
    n = self.iterator.next()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 201, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 221, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 40, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 109, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 109, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 89, in default_collate
    storage = batch[0].storage()._new_shared(numel)
  File "/usr/local/lib/python2.7/dist-packages/torch/storage.py", line 113, in _new_shared
    return cls._new_using_fd(size)
RuntimeError: unable to write to file </torch_3067_1854807876> at /pytorch/torch/lib/TH/THAllocator.c:271

Exception KeyError: KeyError(<weakref at 0x7f376d459890; to 'tqdm' at 0x7f376d37b7d0>,) in <bound method tqdm.__del__ of Training Epoch 0:   0%|                                                                       | 0/131.0 [00:01<?, ?it/s]> ignored
Exception KeyError: KeyError(<weakref at 0x7f376d4597e0; to 'tqdm' at 0x7f376d37bdd0>,) in <bound method tqdm.__del__ of Overall Progress:   0%|                                                      | 0/11 [00:01<?, ?it/s]> ignored

**Comment by qiuzhongwei-USTB** [comment]
![image](https://user-images.githubusercontent.com/34059431/42801075-cbfee7c2-89d0-11e8-8555-ab774dbdf13b.png)
