### ISSUE TITLE
Error for 'bash install.sh'

### ISSUE THREAD

**Issue by irwinherrmann** [NVIDIA/flownet2-pytorch#75]
Env:
cuda: 9.0
cudnn: 9.0
torch: 0.4.1
Ubuntu 16.04

I get the following errors from running 'bash install.sh'
______________________________________________

Compiling correlation kernels by nvcc...
/home/charles/Libraries/OpticalFlow/flownet2-pytorch/networks/correlation_package/src/correlation_cuda.c: In function ‘Correlation_forward_cuda’:
/home/charles/Libraries/OpticalFlow/flownet2-pytorch/networks/correlation_package/src/correlation_cuda.c:20:25: error: dereferencing pointer to incomplete type
   int batchSize = input1->size[0];
                         ^
/home/charles/Libraries/OpticalFlow/flownet2-pytorch/networks/correlation_package/src/correlation_cuda.c:21:30: error: dereferencing pointer to incomplete type
   int nInputChannels = input1->size[1];
                              ^
/home/charles/Libraries/OpticalFlow/flownet2-pytorch/networks/correlation_package/src/correlation_cuda.c:22:27: error: dereferencing pointer to incomplete type
   int inputHeight = input1->size[2];
                           ^
/home/charles/Libraries/OpticalFlow/flownet2-pytorch/networks/correlation_package/src/correlation_cuda.c:23:26: error: dereferencing pointer to incomplete type
   int inputWidth = input1->size[3];
                          ^
/home/charles/Libraries/OpticalFlow/flownet2-pytorch/networks/correlation_package/src/correlation_cuda.c: In function ‘Correlation_backward_cuda’:
/home/charles/Libraries/OpticalFlow/flownet2-pytorch/networks/correlation_package/src/correlation_cuda.c:105:25: error: dereferencing pointer to incomplete type
   int batchSize = input1->size[0];
                         ^
/home/charles/Libraries/OpticalFlow/flownet2-pytorch/networks/correlation_package/src/correlation_cuda.c:106:30: error: dereferencing pointer to incomplete type
   int nInputChannels = input1->size[1];
                              ^
/home/charles/Libraries/OpticalFlow/flownet2-pytorch/networks/correlation_package/src/correlation_cuda.c:107:33: error: dereferencing pointer to incomplete type
   int paddedInputHeight = input1->size[2]+ 2 * pad_size;
                                 ^
/home/charles/Libraries/OpticalFlow/flownet2-pytorch/networks/correlation_package/src/correlation_cuda.c:108:32: error: dereferencing pointer to incomplete type
   int paddedInputWidth = input1->size[3]+ 2 * pad_size;
                                ^
/home/charles/Libraries/OpticalFlow/flownet2-pytorch/networks/correlation_package/src/correlation_cuda.c:110:22: error: dereferencing pointer to incomplete type
   int height = input1->size[2];
                      ^
/home/charles/Libraries/OpticalFlow/flownet2-pytorch/networks/correlation_package/src/correlation_cuda.c:111:21: error: dereferencing pointer to incomplete type
   int width = input1->size[3];
                     ^
Traceback (most recent call last):
  File "build.py", line 31, in <module>
    ffi.build()
  File "/home/charles/Libraries/anaconda2/envs/pytorch/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/charles/Libraries/anaconda2/envs/pytorch/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/charles/Libraries/anaconda2/envs/pytorch/lib/python2.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/charles/Libraries/anaconda2/envs/pytorch/lib/python2.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/charles/Libraries/anaconda2/envs/pytorch/lib/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/charles/Libraries/anaconda2/envs/pytorch/lib/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1
Compiling resample2d kernels by nvcc...
rm: cannot remove 'Resample2d_kernel.o': No such file or directory
In file included from /home/charles/Libraries/anaconda2/envs/pytorch/lib/python2.7/site-packages/torch/lib/include/THC/THCGeneral.h:5:0,
                 from /home/charles/Libraries/anaconda2/envs/pytorch/lib/python2.7/site-packages/torch/lib/include/THC/THC.h:4,
                 from Resample2d_kernel.cu:1:
/home/charles/Libraries/anaconda2/envs/pytorch/lib/python2.7/site-packages/torch/lib/include/TH/THAllocator.h:6:28: fatal error: ATen/Allocator.h: No such file or directory
compilation terminated.
gcc: error: /home/charles/Libraries/OpticalFlow/flownet2-pytorch/networks/resample2d_package/src/Resample2d_kernel.o: No such file or directory
Traceback (most recent call last):
  File "build.py", line 31, in <module>
    ffi.build()
  File "/home/charles/Libraries/anaconda2/envs/pytorch/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/charles/Libraries/anaconda2/envs/pytorch/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/charles/Libraries/anaconda2/envs/pytorch/lib/python2.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/charles/Libraries/anaconda2/envs/pytorch/lib/python2.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/charles/Libraries/anaconda2/envs/pytorch/lib/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/charles/Libraries/anaconda2/envs/pytorch/lib/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1
Compiling channelnorm kernels by nvcc...
rm: cannot remove 'ChannelNorm_kernel.o': No such file or directory
In file included from /home/charles/Libraries/anaconda2/envs/pytorch/lib/python2.7/site-packages/torch/lib/include/THC/THCGeneral.h:5:0,
                 from /home/charles/Libraries/anaconda2/envs/pytorch/lib/python2.7/site-packages/torch/lib/include/THC/THC.h:4,
                 from ChannelNorm_kernel.cu:1:
/home/charles/Libraries/anaconda2/envs/pytorch/lib/python2.7/site-packages/torch/lib/include/TH/THAllocator.h:6:28: fatal error: ATen/Allocator.h: No such file or directory
compilation terminated.

gcc: error: /home/charles/Libraries/OpticalFlow/flownet2-pytorch/networks/channelnorm_package/src/ChannelNorm_kernel.o: No such file or directory
Traceback (most recent call last):
  File "build.py", line 31, in <module>
    ffi.build()
  File "/home/charles/Libraries/anaconda2/envs/pytorch/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/charles/Libraries/anaconda2/envs/pytorch/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/charles/Libraries/anaconda2/envs/pytorch/lib/python2.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/charles/Libraries/anaconda2/envs/pytorch/lib/python2.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/charles/Libraries/anaconda2/envs/pytorch/lib/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/charles/Libraries/anaconda2/envs/pytorch/lib/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1

**Comment by irwinherrmann** [comment]
This was fixed by changing the version of pytorch to 0.2.0.

I then had a segmentation fault when I ran main.py. This segmentation fault was fixed by SWITCHING THE ORDER OF "import torch" and "from tensorboardX import SummaryWriter"

**Comment by ZziTaiLeo** [comment]
> 

So Is there have a solution about pytorch==1.8,cudatoolkit==11.0?
I can't install ,yet
