### ISSUE TITLE
correlation package can't not support pytorch-0.4.1

### ISSUE THREAD

**Issue by lxtGH** [NVIDIA/flownet2-pytorch#76]
/home/lxt/flownet2-pytorch/networks/correlation_package/src/correlation_cuda.c: In function ‘Correlation_forward_cuda’:
/home/lxt/flownet2-pytorch/networks/correlation_package/src/correlation_cuda.c:20:25: error: dereferencing pointer to incomplete type ‘THTensor {aka struct THTensor}’
   int batchSize = input1->size[0];
                         ^
Traceback (most recent call last):
  File "/home/lxt/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/home/lxt/anaconda3/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/lxt/anaconda3/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/lxt/anaconda3/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/lxt/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/lxt/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/lxt/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/lxt/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/lxt/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/lxt/anaconda3/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/lxt/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 31, in <module>
    ffi.build()
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/cffi/api.py", line 690, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/cffi/recompiler.py", line 1515, in recompile
    compiler_verbose, debug)
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1

I am not very familiar with cuda and pytorch source code, need help !!

**Comment by wandering007** [comment]
@lxtGH Have you fixed it? I changed `int batchSize = input1->size[0];` into `int batchSize = THCudaTensor_size(state, input1, 0);` and fixed other similar issues. After that, I successfully built it via Pytorch 0.4.1. However, memory corruption occurs when I run code...

**Comment by lxtGH** [comment]
@wandering007 No,  I met the same error with you, built it successfully, but when I run it, I met memory allocation error. Pytorch.0.4.1 can not run this code, but other versions can.

**Comment by wandering007** [comment]
@lxtGH I guess that it may be caused by some ATen API may change in Pytorch 0.4.1, leading to some functions not safe anymore. But I cannot figure out where it is for now...

**Comment by JiamingSuen** [comment]
https://github.com/ClementPinard/Pytorch-Correlation-extension
ClementPinard wrote a nice correlation module that builds in `0.4.1`(also much faster), thanks Clement!

**Comment by fitsumreda** [comment]
Python36 branch now builds in PtTorch 0.4.1

**Comment by fitsumreda** [comment]
master also supports PyTorch 0.4.1.

**Comment by lxtGH** [comment]
Thanks all !!
