### ISSUE TITLE
NameError: name 'validation_loader' is not defined

### ISSUE THREAD

**Issue by 3togo** [NVIDIA/flownet2-pytorch#91]
When I run "python main.py", I got the following error.  Any pointers to fix it?
My system is pytorch 0.4 , cuda 9.0 

Initializing Adam Optimizer
  [0.001s] amsgrad = False (<class 'bool'>)
  [0.001s] weight_decay = 0 (<class 'int'>)
  [0.001s] eps = 1e-08 (<class 'float'>)
  [0.001s] betas = (0.9, 0.999) (<class 'tuple'>)
  [0.001s] lr = 0.001 (<class 'float'>)
  [0.001s] Operation finished

Overall Progress:   0%|                                                   | 0/10000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "main.py", line 407, in <module>
    validation_loss, _ = train(args=args, epoch=epoch - 1, start_iteration=global_iteration, data_loader=validation_loader, model=model_and_loss, optimizer=optimizer, logger=validation_logger, is_validate=True, offset=offset)
NameError: name 'validation_loader' is not defined
Exception ignored in: <bound method tqdm.__del__ of Overall Progress:   0%|                                                   | 0/10000 [00:00<?, ?it/s]>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tqdm/_tqdm.py", line 889, in __del__
  File "/usr/local/lib/python3.6/dist-packages/tqdm/_tqdm.py", line 1095, in close
  File "/usr/local/lib/python3.6/dist-packages/tqdm/_tqdm.py", line 441, in _decr_instances
  File "/usr/lib/python3.6/_weakrefset.py", line 109, in remove
KeyError: <weakref at 0x7f81a9b6ae08; to 'tqdm' at 0x7f81b8267ac8>

**Comment by 3togo** [comment]
Incorrect parameters input 
problem fixed 

python main.py --inference --model FlowNet2 --save_flow --inference_dataset MpiSintelClean \
--inference_dataset_root /path/to/mpi-sintel/clean/dataset \
--resume /path/to/checkpoints

**Comment by maria-ito** [comment]
Hi,

I have a siliar issue, however running the training (issue: https://github.com/NVIDIA/flownet2-pytorch/issues/103)
Can you please give me any ideas of how I can solve this

**Comment by gmy1234** [comment]
I also have a siliar issue, however running the training (issue: #103)
Can you please give me any ideas of how I can solve this

**Comment by AjithPanja** [comment]
@maria-ito @Estrella1024 Any solution to this issue ?
